"""empty message

Revision ID: 39e81f49b648
Revises: 88bdc20af6fe
Create Date: 2021-09-24 12:37:43.559217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39e81f49b648'
down_revision = '88bdc20af6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='users')
    op.drop_index('username_2', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
    op.create_index('username_2', 'users', ['username'], unique=False)
    op.create_index('username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###
